version: '3.8'

x-logging:
  &default-logging
    driver: 'json-file'
    options:
        max-size: '5m'
        max-file: '1'

services:

    server:
        image: 'zanbaldwin/server'
        build:
            context: './build/docker/server'
            target: '${RUNTIME:-fpm}'
            args:
                NGINX_VERSION: '1.21.0-alpine'
                DOMAIN: '${DOMAIN:-localhost}'
        restart: 'unless-stopped'
        ports:
            -   target: 80
                published: '${WEB_PORT:-80}'
                protocol: 'tcp'
                mode: 'host'
            -   target: 443
                published: '${SSL_PORT:-443}'
                protocol: 'tcp'
                mode: 'host'
        depends_on: [ 'php' ]
        volumes:
            -   type: 'bind'
                source: './public'
                target: '/srv/public'
                read_only: true
            -   type: 'bind'
                source: '/etc/letsencrypt'
                target: '/etc/letsencrypt'
                read_only: true
        logging: *default-logging

    php:
        image: 'zanbaldwin/php'
        build:
            context: './build/docker/php'
            target: '${RUNTIME:-fpm}'
            args:
                PHP_VERSION: '8.0-fpm-alpine3.13'
                COMPOSER_VERSION: '2.0.9'
        restart: 'unless-stopped'
        depends_on: [ 'database' ]
        volumes:
            -   type: 'bind'
                source: './'
                target: '/srv'
                read_only: false
        logging: *default-logging

    database:
        image: 'zanbaldwin/database'
        build:
            context: './build/docker/database'
            args:
                MYSQL_VERSION: '8.0.25'
        restart: 'unless-stopped'
        environment:
            MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/dbpass'
            MYSQL_DATABASE: '${DB_NAME:-main}'
        volumes:
            -   type: 'bind'
                source: '/var/lib/mysql'
                target: '/var/lib/mysql'
                read_only: false
        secrets:
            -   'dbpass'
        logging: *default-logging

secrets:
    dbpass:
        file: './build/.secrets/dbpass'
